export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const GENERATE_RECIPES = 'GENERATE_RECIPES';
export const GET_RECIPE = 'GET_RECIPE';
export const REQUEST_RECIPES = 'REQUEST_RECIPES';
export const REQUEST_RECIPE = 'REQUEST_RECIPE';
